// ===================================================================
//  HISTORIAS DESTACADAS · Pureza Natural
//  Siete destacadas en el orden en que una persona decide comprar.
//  Instagram pasa sola a la siguiente destacada, así que cada una
//  termina invitando a la que sigue.
//  *asteriscos* = palabras resaltadas.
//  Regla de marca: "purificador", nunca "filtro" (los testimonios van textuales).
// ===================================================================

window.CONFIG = {
  cuenta: '@purezanatural',
  whatsapp: '313 269 6087',
};

// fondo: 'niebla' (claro) · 'verde' (oscuro) · 'agua' (azul suave)
// plantilla: foto · frase · cifra · lista · cita · siguiente
// sticker: el sticker nativo de Instagram que pones encima al subirla (no va en la imagen)
window.DESTACADAS = [
  {
    id: 'nosotros', nombre: 'Nosotros', icono: 'manos',
    para: 'Quiénes somos: quién está detrás, dónde estamos y cómo te atendemos.',
    historias: [
      { plantilla: 'frase', fondo: 'verde',
        kicker: 'Quiénes somos', titulo: 'Somos Pureza *Natural.*',
        texto: 'Distribuidor autorizado de AguaLogic en Villavicencio, Meta.' },
      { plantilla: 'foto', fondo: 'niebla', foto: 'familia.jpg',
        kicker: 'Lo que hacemos', titulo: 'Llevamos agua pura *a tu casa.*',
        texto: 'Purificadores de vidrio, barro y acero. Sin luz y sin instalación.' },
      { plantilla: 'lista', fondo: 'niebla',
        kicker: 'Cómo te atendemos', titulo: 'Contigo antes *y después.*',
        pasos: [
          ['Te ayudamos a elegir', 'Por WhatsApp, antes de comprar.'],
          ['Te enseñamos a usarlo', 'El curado inicial y el lavado de cada mes.'],
          ['Respondemos por la garantía', 'Si hay un defecto de fábrica, hacemos el trámite con AguaLogic.'],
        ] },
      { plantilla: 'frase', fondo: 'agua',
        kicker: 'Atención digital', titulo: 'Te contestamos *nosotros.*',
        texto: 'No tenemos local al público. Todo va por WhatsApp y DM, y te respondemos directo.',
        sticker: { tipo: 'Preguntas', texto: 'Pregúntanos lo que quieras' } },
      { plantilla: 'frase', fondo: 'verde',
        kicker: 'Lo que nos mueve', titulo: 'Claridad *que cuida.*',
        texto: 'Agua pura en tu mesa, sin hervir y sin cargar botellones.' },
      { plantilla: 'siguiente', fondo: 'niebla', sigue: 'empieza',
        titulo: '¿Y cómo funciona *el purificador?*' },
    ],
  },
  {
    id: 'empieza', nombre: 'Empieza', icono: 'gota',
    para: 'Quien llega por primera vez: qué es y cómo purifica, en un minuto.',
    historias: [
      { plantilla: 'foto', fondo: 'niebla', foto: 'img/purificador-catalogo.jpg', completa: true,
        kicker: 'Empieza aquí', titulo: 'Agua pura, *hecha de barro.*',
        texto: 'Así funciona el purificador AguaLogic, en un minuto.' },
      { plantilla: 'frase', fondo: 'verde',
        kicker: 'Lo que vivimos en casa', titulo: 'Hervir, esperar, cargar, *repetir.*',
        texto: 'Y el botellón se acaba justo el domingo.',
        sticker: { tipo: 'Encuesta', texto: '¿Cuál te pasa a ti? · Hiervo el agua · Compro botellón' } },
      { plantilla: 'purificador', fondo: 'niebla',
        kicker: 'Cómo purifica', titulo: 'Llenas la vasija. *Cae gota a gota.*',
        texto: 'El barro purifica despacio y la gravedad hace el resto. Sirves abajo.' },
      { plantilla: 'lista', fondo: 'agua',
        kicker: 'Adentro del barro', titulo: 'Tres capas, *cero electricidad.*',
        pasos: [
          ['Arcilla', 'Poros de 0,2 a 0,5 micras. Ahí se quedan sedimentos, bacterias y parásitos.'],
          ['Carbón activado', 'Le quita el cloro, el olor y ese sabor raro.'],
          ['Plata coloidal', 'Actúa sobre coliformes y E. coli.'],
        ] },
      { plantilla: 'frase', fondo: 'verde',
        kicker: 'Así de simple', titulo: 'Sin luz. Sin instalación. *Sin botellones.*',
        texto: 'Lo pones en el mesón y listo. No va a la tubería ni a un enchufe.',
        sticker: { tipo: 'Quiz', texto: '¿A qué se conecta? · A la llave · A la luz · A nada (correcta)' } },
      { plantilla: 'siguiente', fondo: 'niebla', sigue: 'pruebas',
        titulo: '¿Y eso *quién lo comprobó?*' },
    ],
  },
  {
    id: 'pruebas', nombre: 'Pruebas', icono: 'matraz',
    para: 'Quien duda: resultados de laboratorio, con fuente y sin exagerar.',
    historias: [
      { plantilla: 'frase', fondo: 'verde',
        kicker: 'Evidencia, no promesas', titulo: 'Lo midió el laboratorio, *no nosotros.*',
        texto: 'Universidad Nacional, en un laboratorio acreditado por el IDEAM, y Universidad del Magdalena. Comparado con la Resolución 2115 de 2007.' },
      { plantilla: 'cifra', fondo: 'niebla',
        cifra: '95,2 %', etiqueta: 'menos turbiedad',
        texto: 'De 40,5 a 1,94 UNT. El máximo permitido es 2.' },
      { plantilla: 'cifra', fondo: 'agua',
        cifra: '100 %', etiqueta: 'de coliformes y E. coli removidos',
        texto: 'En las muestras analizadas.' },
      { plantilla: 'cifra', fondo: 'niebla',
        cifra: '84,8 %', etiqueta: 'menos arsénico',
        texto: 'De 21,7 a 3,3 µg/L.' },
      { plantilla: 'frase', fondo: 'niebla',
        kicker: 'Ojo con esto', titulo: '¿Quieres ver los *informes completos?*',
        texto: 'Te los mandamos por WhatsApp. Son resultados de esas muestras, y cada fuente de agua es distinta.',
        sticker: { tipo: 'Enlace', texto: 'Pedir los informes → wa.me/573132696087' } },
      { plantilla: 'siguiente', fondo: 'verde', sigue: 'clientes',
        titulo: 'Ahora, lo que cuentan *en casa.*' },
    ],
  },
  {
    id: 'clientes', nombre: 'Clientes', icono: 'globo',
    para: 'Prueba social: palabras exactas de clientes reales.',
    historias: [
      { plantilla: 'foto', fondo: 'niebla', foto: 'img/cocina-purificador.jpg', completa: true,
        kicker: 'Lo que dicen en casa', titulo: 'Palabras de ellos, *no nuestras.*',
        texto: 'Copiadas tal cual nos las escribieron.' },
      { plantilla: 'cita', fondo: 'verde', autor: 'Chio Duque',
        cita: 'Se ve en el filtro de barro toda la suciedad que filtra del agua. No conozco la vida diaria sin los filtros de AguaLogic.' },
      { plantilla: 'cita', fondo: 'niebla', autor: 'Camilo Valbuena',
        cita: 'Excelente alternativa para tomar un agua purificada y de calidad, de vidrio y materiales en general ecológicos.' },
      { plantilla: 'cita', fondo: 'agua', autor: 'Diana Cruz',
        cita: 'No cambio la vida diaria sin los filtros de AguaLogic.' },
      { plantilla: 'frase', fondo: 'niebla',
        kicker: '¿Ya lo tienes?', titulo: 'Muéstranos *tu rincón.*',
        texto: 'Sube una foto del purificador en tu cocina y la compartimos aquí.',
        sticker: { tipo: 'Agregar el tuyo', texto: 'Mi purificador en casa' } },
      { plantilla: 'siguiente', fondo: 'verde', sigue: 'cuentas',
        titulo: '¿Y cuánta plata *te ahorras?*' },
    ],
  },
  {
    id: 'cuentas', nombre: 'Cuentas', icono: 'botellon',
    para: 'El argumento de plata y de espalda: lo que se va en botellones.',
    historias: [
      { plantilla: 'frase', fondo: 'niebla',
        kicker: 'Las cuentas claras', titulo: '¿Cuánto se te va *en botellones?*',
        texto: 'Hicimos la cuenta con una casa normal.',
        sticker: { tipo: 'Encuesta', texto: '¿Cuántos compras al mes? · 1 a 4 · 5 o más' } },
      { plantilla: 'cifra', fondo: 'verde',
        cifra: '$66.000', etiqueta: 'al mes',
        texto: '6 botellones de $11.000. Es precio de referencia, pon el que pagas tú.' },
      { plantilla: 'cifra', fondo: 'niebla',
        cifra: '$792.000', etiqueta: 'al año',
        texto: 'En dos años son $1.584.000.' },
      { plantilla: 'cifra', fondo: 'agua',
        cifra: '1.440 kg', etiqueta: 'cargados al año',
        texto: 'Bajarlos del carro, subir escaleras, voltearlos en el dispensador.' },
      { plantilla: 'frase', fondo: 'verde',
        kicker: 'Y el purificador', titulo: 'La vasija de barro *dura 2 años.*',
        texto: 'Cuando la cambias, la vieja te sirve de matera.' },
      { plantilla: 'siguiente', fondo: 'niebla', sigue: 'pedir',
        titulo: 'Haz la cuenta *con nosotros.*' },
    ],
  },
  {
    id: 'pedir', nombre: 'Pedir', icono: 'casa', acento: true,
    para: 'Quien ya se decidió: pasos, medidas, envíos y garantía. La única con punto arcilla.',
    historias: [
      { plantilla: 'lista', fondo: 'niebla',
        kicker: 'Así lo pides', titulo: 'Tres pasos y *llega a tu casa.*',
        pasos: [
          ['Nos escribes', 'Por WhatsApp o por DM.'],
          ['Te damos el precio', 'Del modelo que te sirve, con el envío a tu municipio.'],
          ['Coordinamos la entrega', 'Y te enseñamos a usarlo.'],
        ] },
      { plantilla: 'foto', fondo: 'niebla', foto: 'img/despiece.jpg', completa: true,
        kicker: 'El purificador', titulo: '20 litros de *vidrio, barro y acero.*',
        texto: '45 cm de alto, 34,5 cm de diámetro y unos 14 kg. Los 20 litros incluyen la vasija.' },
      { plantilla: 'frase', fondo: 'agua',
        kicker: 'Envíos', titulo: 'Villavicencio y *el Meta.*',
        texto: 'También Acacías, Restrepo, Cumaral y municipios cercanos. Fuera de Villavicencio el envío tiene un costo adicional.' },
      { plantilla: 'frase', fondo: 'verde',
        kicker: 'Garantía AguaLogic', titulo: 'Si viene con defecto, *el trámite es nuestro.*',
        texto: 'Si hay un defecto de fábrica, lo gestionamos con AguaLogic por ti.' },
      { plantilla: 'frase', fondo: 'niebla', boton: 'WhatsApp 313 269 6087',
        kicker: 'Tu turno', titulo: 'Este mes, *sin botellón.*',
        texto: 'Escríbenos y hoy mismo te damos el precio.',
        sticker: { tipo: 'Enlace', texto: 'Pedir el mío → wa.me/573132696087' } },
      { plantilla: 'siguiente', fondo: 'verde', sigue: 'cuidados',
        titulo: '¿Ya llegó? *Así lo cuidas.*' },
    ],
  },
  {
    id: 'cuidados', nombre: 'Cuidados', icono: 'matera',
    para: 'Posventa: para clientes. Ahorra preguntas repetidas por WhatsApp.',
    historias: [
      { plantilla: 'frase', fondo: 'verde',
        kicker: 'Ya lo tienes', titulo: 'Así lo cuidas *para que dure.*',
        texto: 'Es poquito y es una vez al mes.' },
      { plantilla: 'frase', fondo: 'agua',
        kicker: 'Antes del primer uso', titulo: 'El curado *te lo explicamos.*',
        texto: 'Si todavía no lo hiciste, escríbenos y te guiamos paso a paso.',
        sticker: { tipo: 'Preguntas', texto: '¿Qué duda tienes del purificador?' } },
      { plantilla: 'lista', fondo: 'niebla',
        kicker: 'Una vez al mes', titulo: 'El lavado',
        pasos: [
          ['Vasija de barro', 'Solo con agua limpia. Sin jabón ni cloro.'],
          ['Vidrio, tapa y llave', 'Con agua y jabón.'],
          ['Ojo con el vidrio', 'No lo pongas boca abajo ni le eches agua caliente.'],
        ] },
      { plantilla: 'foto', fondo: 'niebla', foto: 'barro.jpg',
        kicker: 'Cada 2 años', titulo: 'Cambias la vasija *de barro.*',
        texto: 'La vieja no se bota. Siembra una planta en ella.' },
      { plantilla: 'cierre', fondo: 'verde',
        titulo: 'Claridad *que cuida.*', texto: 'Pureza Natural · Distribuidor autorizado de AguaLogic' },
    ],
  },
];
